" --- 插件运行时路径配置 (由清理脚本添加) ---
set rtp+=~/.vim/NERD_Tree
set rtp+=~/.vim/YouCompleteMe
set rtp+=~/.vim/Taglist

" --- 以下内容拷贝自 /etc/vim/vimrc ---

" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

runtime! debian.vim

" Vim will load $VIMRUNTIME/defaults.vim if the user does not have a vimrc.
" This happens after /etc/vim/vimrc(.local) are loaded, so it will override
" any settings in these files.
" If you don't want that to happen, uncomment the below line to prevent
" defaults.vim from being loaded.
" let g:skip_defaults_vim = 1

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"filetype plugin indent on

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd            " Show (partial) command in status line.
"set showmatch          " Show matching brackets.
"set ignorecase         " Do case insensitive matching
"set smartcase          " Do smart case matching
"set incsearch          " Incremental search
"set autowrite          " Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned



" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif


"--自动补全配置--
set completeopt=longest,menu "让Vim的补全菜单行为与一般IDE一致(参考VimTip1228)
autocmd InsertLeave * if pumvisible() == 0|pclose|endif "离开插入模式后自动关闭预览窗口
inoremap <expr> <CR>       pumvisible() ? "<C-y>" : "<CR>" "回车即选中当前项
"上下左右键的行为 会显示其他信息
inoremap <expr> <Down>     pumvisible() ? "<C-n>" : "<Down>"
inoremap <expr> <Up>       pumvisible() ? "<C-p>" : "<Up>"
inoremap <expr> <PageDown> pumvisible() ? "<PageDown>\<C-p>\<C-n>" : "<PageDown>"
inoremap <expr> <PageUp>   pumvisible() ? "<PageUp>\<C-p>\<C-n>" : "<PageUp>"
"youcompleteme  默认tab  s-tab 和自动补全冲突
"let g:ycm_key_list_select_completion=['<c-n>']
"let g:ycm_key_list_select_completion = ['<Down>']
"let g:ycm_key_list_previous_completion=['<c-p>']
"let g:ycm_key_list_previous_completion = ['<Up>']
let g:ycm_confirm_extra_conf=0 "关闭加载.ycm_extra_conf.py提示
"let g:ycm_confirm_extra_conf='~/.ycm_extra_conf.py' 
let g:ycm_collect_identifiers_from_tags_files=1 " 开启 YCM 基于标签引擎
let g:ycm_min_num_of_chars_for_completion=1 " 从第2个键入字符就开始罗列匹配项
let g:ycm_cache_omnifunc=0 " 禁止缓存匹配项,每次都重新生成匹配项
let g:ycm_seed_identifiers_with_syntax=1 " 语法关键字补全
nnoremap <F5> :YcmForceCompileAndDiagnostics<CR> "force recomile with syntatic
"nnoremap <leader>lo :lopen<CR> "open locationlist
"nnoremap <leader>lc :lclose<CR> "close locationlist
inoremap <leader><leader> <C-x><C-o>
"在注释输入中也能补全
let g:ycm_complete_in_comments = 1
"关闭语法动态检查
let g:ycm_show_diagnostics_ui = 0

"--常用设置--
set noswapfile   " 设置不保存备份文件
set nu           " 设置行号
set showmatch    " 设置匹配模式，显示匹配的括号
set mouse=a      " Enable mouse usage (all modes)
set clipboard=unnamedplus "设置剪切板复制粘贴功能与系统的剪切板关联
syntax on        " 设置语法高亮 
set smartindent  " 设置智能对齐
set tabstop=4    " 设置tab按键长度为4
set ts=4                 "Tab替换为空格
set expandtab
%retab!
"--自动删除vim中行尾空格--
autocmd BufWritePre *.c :%s/\s\+$//e
autocmd BufWritePre *.h :%s/\s\+$//e
autocmd BufWritePre *.java :%s/\s\+$//e

"--搜索设置--
set incsearch    " 输入字符串就显示匹配点
set hlsearch     " 高亮度搜寻

"--ctags设置--
" 如果当前目录没找到tags文件就依次到上层目录查找tags文件
set tags=tags;/ 
" 按下F4重新生成tag文件，并更新taglist
map <F4> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR><CR> :TlistUpdate<CR>
imap <F4> <ESC>:!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR><CR> :TlistUpdate<CR>

"--Tlist设置--
" F9键映射为:TlistToggle的快捷键
map <silent> <F9> :TlistToggle<cr>  
let Tlist_Ctags_Cmd='ctags' "因为我们放在环境变量里，所以可以直接执行
let Tlist_Use_Right_Window=0 "让窗口显示在右边，0的话就是显示在左边
let Tlist_Show_One_File=0 "让taglist可以同时展示多个文件的函数列表
let Tlist_File_Fold_Auto_Close=1 "非当前文件，函数列表折叠隐藏
let Tlist_Exit_OnlyWindow=1 "当taglist是最后一个分割窗口时，自动推出vim
"是否一直处理tags.1:处理;0:不处理
let Tlist_Process_File_Always=1 "实时更新tags
let Tlist_Inc_Winwidth=0

"-- NERDTree setting --
map <silent> <F2> :NERDTreeToggle<CR>

"-- WinManager setting --
let g:winManagerWindowLayout='FileExplorer|TagList|NERDTree' " 设置我们要管理的插件 
"let g:persistentBehaviour=0 " 如果所有编辑文件都关闭了，退出vim
map <silent> <F8> :WMToggle<cr>